networks:
  jimmybottt:
    driver: bridge

services:

  bot:
    init: true
    container_name: bot
    image: bot
    build:
      context: ./requirements/bot
    env_file:
      - ./.env
    restart: unless-stopped
    networks :
      - jimmybottt

  database:
    init: true
    container_name: database
    image: database
    build:
      context: ./requirements/database
    env_file:
      - path: ./.env
    restart: unless-stopped
    networks :
      - jimmybottt
    volumes:
      - database:/var/lib/mysql

volumes:
  database :
    driver : local
    driver_opts:
      type: none
      device : mariadb
      o: bind